version: '3'
services:
  redis:
    image: redis:alpine
  messaging-1:
    build:
      context: ./
      dockerfile: Dockerfile
    image: david/messaging
    ports:
      - 8080
    networks:
      - network1
  messaging-2:
    build:
      context: ./
      dockerfile: Dockerfile
    image: david/messaging
    ports:
      - 8080
    networks:
      - network1
  messaging-3:
    build:
      context: ./
      dockerfile: Dockerfile
    image: david/messaging
    ports:
      - 8080
    networks:
      - network1

networks:
  network1: