version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - network1
  messaging-1:
    build:
      context: ./
      dockerfile: Dockerfile
    image: david/messaging
    ports:
      - 8080
    networks:
      - network1
    depends_on:
      - redis
    environment:
      - spring.redis.host=redis
  messaging-2:
    build:
      context: ./
      dockerfile: Dockerfile
    image: david/messaging
    ports:
      - 8080
    networks:
      - network1
    depends_on:
      - redis
    environment:
      - spring.redis.host=redis
  messaging-3:
    build:
      context: ./
      dockerfile: Dockerfile
    image: david/messaging
    ports:
      - 8080
    networks:
      - network1
    depends_on:
      - redis
    environment:
      - spring.redis.host=redis

networks:
  network1